version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  test:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose up -d
      - run: pip install poetry
      - run: cd app/ && poetry  install && poetry run playwright install --with-deps
      - run: cd app/ && poetry run pytest
  custom-aws-ecr:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run: cd app/ && docker build --no-cache --progress=plain -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/aws-cicd:latest .
      - aws-ecr/push-image:
          repo: aws-cicd
      - run: aws ecs update-service --cluster aws-cicd-demo --service serv-2 --force-new-deployment
          
  
workflows:
  integration_tests:
    jobs:
      - test
      - custom-aws-ecr:
          requires:
            - test
