version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose up -d
      - run: pip install poetry
      - run: cd app/ && poetry  install && poetry run playwright install --with-deps
      - run: cd app/ && bash test.sh
      - run: cd app/ && poetry run pytest
  custom-aws-ecr:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run: cd app/ && docker build --no-cache --progress=plain -t app:latest .
      - run: docker tag app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}-1.amazonaws.com/aws-cicd:latest
      - aws-ecr/push-image:
          repo: aws-cicd 
          
  
workflows:
  integration_tests:
    jobs:
      - test
  custom-build-and-deploy:
    jobs:
      - custom-aws-ecr